version: '3'

services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ankish
      POSTGRES_DB: questionnaire 
    ports:
      - "5432:5432"
    volumes:
      - postgresdb_data:/data/db

  app: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
      - "5173:5173"
      - "5174:5174"
    # environment:
      # - DATABASE_URL="postgresql://postgres:ankish@postgres:5432/test_questionnaire?schema=public"
    depends_on:
      - postgresdb
volumes:
  postgresdb_data:
