FROM node:14

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

COPY ./apps/student/package.json ./apps/student/package.json
COPY  ./apps/teacher/package.json ./apps/teacher/package.json
COPY ./apps/server/package.json  ./apps/server/package.json

RUN npm install

COPY . .

EXPOSE 3000 5173 5174

CMD ["npm", "run", "dev"]