version: '3'

services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ankish
      POSTGRES_DB: questionnaire
    ports:
      - "5432:5432"
    volumes:
      - postgresdb_data:/data/db

  api:
    build: 
      context: ../
      dockerfile: ./docker/api.nestjs.Dockerfile
    restart: unless-stopped
    depends_on:
      - postgresdb
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - "/home/ankish20000nayak/Projects/personal-projects/questionnaire/apps/api:/usr/src/app/apps/api:delegated"
      # packages prisma folder
      - "/home/ankish20000nayak/Projects/personal-projects/questionnaire/packages/prisma:/usr/src/app/packages/prisma:delegated"
      # packages types folder 
      - "/home/ankish20000nayak/Projects/personal-projects/questionnaire/packages/types:/usr/src/app/packages/types:delegated"
    tty: true
  # api:
  #   build:
  #     context: ../
  #     dockerfile: ./docker/api.Dockerfile
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgresdb
  #   volumes:
  #     # binds 
  #     # server 
  #     - "/home/ankish20000nayak/Projects/personal-projects/questionnaire/apps/server:/usr/src/app/apps/server:delegated"
  #     # packages prisma folder 
  #     - "/home/ankish20000nayak/Projects/personal-projects/questionnaire/packages/prisma:/usr/src/app/packages/prisma:delegated"
  #     # packages types folder 
  #     - "/home/ankish20000nayak/Projects/personal-projects/questionnaire/packages/types:/usr/src/app/packages/types:delegated"
  #   tty: true
  frontend:
    build:
      context: ../
      dockerfile: ./docker/frontend.Dockerfile
      args:
        - SERVER_HOST=localhost
        - SERVER_PORT=3000
    ports:
      - "5173:5173"
      - "5174:5174"
    depends_on:
      - api
    volumes:
      # binds
      # student frontend
      - "/home/ankish20000nayak/Projects/personal-projects/questionnaire/apps/student:/usr/src/app/apps/student:delegated"
      # teacher frontend
      - "/home/ankish20000nayak/Projects/personal-projects/questionnaire/apps/teacher:/usr/src/app/apps/teacher:delegated"
      # common packages ui 
      - "/home/ankish20000nayak/Projects/personal-projects/questionnaire/packages/ui:/usr/src/app/packages/ui:delegated"
      # packages types folder 
      - "/home/ankish20000nayak/Projects/personal-projects/questionnaire/packages/types:/usr/src/app/packages/types:delegated"
    tty: true

  linuxDistro:
    image: busybox:glibc
    command: [ "/bin/busybox", "httpd", "-f", "-p", "8080" ]
    ports:
      - "8080:8080"

volumes:
  postgresdb_data:
