version: '3'

services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ankish
      POSTGRES_DB: questionnaire
    ports:
      - "5432:5432"
    volumes:
      - postgresdb_data:/data/db

  api:
    build:
      context: ../
      dockerfile: ./docker/api.Dockerfile
    restart: always
    ports:
      - "3000:3000"
      # - "5173:5173"
      # - "5174:5174"
      # environment:
      # - DATABASE_URL="postgresql://postgres:ankish@postgres:5432/test_questionnaire?schema=public"
    depends_on:
      - postgresdb
  frontend:
    build:
      context: ../
      dockerfile: ./docker/frontend.Dockerfile
      args: 
        - SERVER_HOST=api
        - SERVER_PORT=3000
    ports:
      - "5173:5173"
      - "5174:5174"

  linuxDistro:
    image: busybox:glibc
    command: [ "/bin/busybox", "httpd", "-f", "-p", "8080" ]
    ports:
      - "8080:8080"

volumes:
  postgresdb_data:
