/* tslint:disable */
/* eslint-disable */
/**
 * Questionnaire Open Api
 * Questionnaire api description
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudentLoginDto
 */
export interface StudentLoginDto {
    /**
     * 
     * @type {string}
     * @memberof StudentLoginDto
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof StudentLoginDto
     */
    password: string;
}

/**
 * Check if a given object implements the StudentLoginDto interface.
 */
export function instanceOfStudentLoginDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function StudentLoginDtoFromJSON(json: any): StudentLoginDto {
    return StudentLoginDtoFromJSONTyped(json, false);
}

export function StudentLoginDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentLoginDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function StudentLoginDtoToJSON(value?: StudentLoginDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
    };
}

