/* tslint:disable */
/* eslint-disable */
/**
 * Questionnaire Open Api
 * Questionnaire api description
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeacherSignupDto
 */
export interface TeacherSignupDto {
    /**
     * 
     * @type {string}
     * @memberof TeacherSignupDto
     */
    firstname: string;
    /**
     * 
     * @type {string}
     * @memberof TeacherSignupDto
     */
    lastname: string;
    /**
     * 
     * @type {string}
     * @memberof TeacherSignupDto
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof TeacherSignupDto
     */
    password: string;
}

/**
 * Check if a given object implements the TeacherSignupDto interface.
 */
export function instanceOfTeacherSignupDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "firstname" in value;
    isInstance = isInstance && "lastname" in value;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function TeacherSignupDtoFromJSON(json: any): TeacherSignupDto {
    return TeacherSignupDtoFromJSONTyped(json, false);
}

export function TeacherSignupDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeacherSignupDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstname': json['firstname'],
        'lastname': json['lastname'],
        'username': json['username'],
        'password': json['password'],
    };
}

export function TeacherSignupDtoToJSON(value?: TeacherSignupDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstname': value.firstname,
        'lastname': value.lastname,
        'username': value.username,
        'password': value.password,
    };
}

