/* tslint:disable */
/* eslint-disable */
/**
 * Questionnaire Open Api
 * Questionnaire api description
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeacherLoginDto
 */
export interface TeacherLoginDto {
    /**
     * 
     * @type {string}
     * @memberof TeacherLoginDto
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof TeacherLoginDto
     */
    password: string;
}

/**
 * Check if a given object implements the TeacherLoginDto interface.
 */
export function instanceOfTeacherLoginDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function TeacherLoginDtoFromJSON(json: any): TeacherLoginDto {
    return TeacherLoginDtoFromJSONTyped(json, false);
}

export function TeacherLoginDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeacherLoginDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function TeacherLoginDtoToJSON(value?: TeacherLoginDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
    };
}

